### ISSUE TITLE
Possible double overlay of subtitles

### ISSUE THREAD

**Issue by appa561** [obs-ai/obs-localvocal#26]
I tested LV the entire stream last night. While mostly good, base still struggles. I am unsure if it is only my annunciation of words or a limitation of the base model. Overall, far better than expected and the project is/was well received. 

At one point, a viewer commented they were seeing a double overlay of the subtitles. Upon reviewing the VOD, I do not see it. I will include a clip of the area and a screen shot from the viewer. If I can capture this again, should I have "debug" selected for the log level? Right now, it is "info"
![image](https://github.com/royshil/obs-localvocal/assets/145307940/781ccdc1-0412-4a1b-9ea3-211dd043b557)
[Twitch Highlight](https://www.twitch.tv/videos/1933059633) The issue shown in the screenshot happens about halfway through, around the 2:20 point.

**Comment by royshil** [comment]
This looked super cool! 
The captions worked pretty well , only a few minor glitches

For the double overlay
Did you have a text source on your broadcast as well as "send to stream" enabled?
Because that would be a double overlay, one from your broadcast and one for the user's captions display.
I could also see a double overlay just watching the twitch stream you linked. It because I enabled CC and the stream had it displayed as well.

You can either disable the captions display or disable the send to stream.
And then there won't be doubling of the captions.

**Comment by appa561** [comment]
"send to stream" is that the "stream captions" checkbox in the filter settings?

There is a text source created during the installation that is named subtitles. The only thing I've done there is move it a smidge. What I do and do not understand... Like Joe, my viewer, you said you are seeing a double overlay in the Twitch Highlight I provided. I am not. Maybe I do not see a setting for turning CC off or on since I am watching a VOD for which I am the broadcaster?

BTW, I will be adding a panel to my Twitch About area highlighting the project. As I mentioned, I have quite the international audience. Last night, we had multiple languages represented during the stream at some point: English, Norwegian, Spanish, Vietnamese, Polish, and Bulgarian.

Other than streamers who happen to be multi-lingual, I think I am the only one in my game category that is actively seeking to reach a truly international audience. Most of the streamers for my game category will work in their native language and limit chat to that. Some that are multi-lingual may allow an alternative like English. Given such a wide reach of my stream, I really want this to succeed. If you watch the entire stream, as I talk about the LV project, especially the Spanish speaking players, all are excited about LV working.

**Comment by mrfragger** [comment]
yea if you enable CC and in closed captions options to green text it'll show
![image](https://github.com/royshil/obs-localvocal/assets/80211672/c515b8d5-51bc-40b4-adcc-225037617007)

**Comment by appa561** [comment]
> yea if you enable CC and in closed captions options to green text it'll show ![image](https://user-images.githubusercontent.com/80211672/270196470-c515b8d5-51bc-40b4-adcc-225037617007.png)

Where is this set in LV and Twitch?

**Comment by royshil** [comment]
@appa561 
this is a setting in Twitch
![image](https://github.com/royshil/obs-localvocal/assets/441170/624e9ce5-0b3a-4b5c-a185-39548dc3a40a)
every viewer can enable/disable CC for his view.
but since youre both streaming captions to Twitch as well as showing them on screen through OBS text source overlay - it appears they show up double.

**Comment by royshil** [comment]
i think this isseu is safe to close
